"""empty message

Revision ID: 1232247eda4b
Revises: fe68cd98438c
Create Date: 2021-10-20 04:53:08.234781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1232247eda4b'
down_revision = 'fe68cd98438c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ventas', sa.Column('metodo_pago', sa.String(length=120), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ventas', 'metodo_pago')
    # ### end Alembic commands ###
