"""empty message

Revision ID: 2e8d1f9e469c
Revises: 
Create Date: 2021-10-08 13:24:20.756112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e8d1f9e469c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_cat', sa.String(length=120), nullable=True),
    sa.Column('descripcion_cat', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detalleingreso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_ingreso', sa.Integer(), nullable=False),
    sa.Column('id_articulo', sa.Integer(), nullable=False),
    sa.Column('cantidad_di', sa.Integer(), nullable=False),
    sa.Column('precio_di', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detalleventa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingreso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.String(length=120), nullable=False),
    sa.Column('proveedor', sa.String(length=120), nullable=False),
    sa.Column('tipo_comprobante_ing', sa.String(length=120), nullable=False),
    sa.Column('numero_comprobante_ing', sa.String(length=120), nullable=False),
    sa.Column('fecha_ing', sa.String(length=50), nullable=False),
    sa.Column('impuesto_ing', sa.Float(), nullable=False),
    sa.Column('total_ing', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('metodopago',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('num_pago', sa.String(length=120), nullable=True),
    sa.Column('nombre_metpag', sa.String(length=120), nullable=True),
    sa.Column('otros_datos', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('productos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=True),
    sa.Column('codigo_barras', sa.String(length=120), nullable=True),
    sa.Column('id_categoria', sa.Integer(), nullable=True),
    sa.Column('precio_venta', sa.Float(precision=50), nullable=True),
    sa.Column('image', sa.String(length=300), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('fecha_ingreso', sa.String(length=50), nullable=False),
    sa.Column('costo_compra', sa.Float(precision=50), nullable=False),
    sa.Column('factura_proveedor', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_barras')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('last_name', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=120), nullable=False),
    sa.Column('theme', sa.String(length=120), nullable=True),
    sa.Column('font_preference', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('negocios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_negocio', sa.String(length=120), nullable=False),
    sa.Column('trabajadores', sa.String(length=120), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_rol', sa.Integer(), nullable=True),
    sa.Column('descripcion', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['nombre_rol'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ventas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('tipo_comprobante', sa.String(length=120), nullable=False),
    sa.Column('numero_comprobante', sa.String(length=120), nullable=False),
    sa.Column('fecha', sa.String(length=50), nullable=False),
    sa.Column('impuesto', sa.Float(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ventas')
    op.drop_table('role')
    op.drop_table('negocios')
    op.drop_table('users')
    op.drop_table('productos')
    op.drop_table('metodopago')
    op.drop_table('ingreso')
    op.drop_table('detalleventa')
    op.drop_table('detalleingreso')
    op.drop_table('categoria')
    # ### end Alembic commands ###
