"""empty message

Revision ID: 493b743b63ee
Revises: 3e9686b580f5
Create Date: 2021-10-07 06:33:54.023524

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '493b743b63ee'
down_revision = '3e9686b580f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingreso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.String(length=120), nullable=False),
    sa.Column('proveedor', sa.String(length=120), nullable=False),
    sa.Column('tipo_comprobante_ing', sa.String(length=120), nullable=False),
    sa.Column('numero_comprobante_ing', sa.String(length=120), nullable=False),
    sa.Column('fecha_ing', sa.String(length=50), nullable=False),
    sa.Column('impuesto_ing', sa.Float(), nullable=False),
    sa.Column('total_ing', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('productos', 'proveedor')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productos', sa.Column('proveedor', mysql.VARCHAR(length=50), nullable=False))
    op.drop_table('ingreso')
    # ### end Alembic commands ###
