"""empty message

Revision ID: 5b227271b081
Revises: c419e6ffbda4
Create Date: 2021-10-06 14:41:45.205210

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5b227271b081'
down_revision = 'c419e6ffbda4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('negocio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_negocio', sa.String(length=120), nullable=False),
    sa.Column('id_dueño_negocio', sa.Integer(), nullable=False),
    sa.Column('trabajadores', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id', 'id_dueño_negocio'),
    sa.UniqueConstraint('nombre_negocio'),
    sa.UniqueConstraint('nombre_negocio')
    )
    op.drop_index('nombre_negocio', table_name='Negocio')
    op.drop_table('Negocio')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Negocio',
    sa.Column('id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_dueño_negocio', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('trabajadores', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('nombre_negocio', mysql.VARCHAR(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id', 'id_dueño_negocio'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('nombre_negocio', 'Negocio', ['nombre_negocio'], unique=False)
    op.drop_table('negocio')
    # ### end Alembic commands ###
