"""empty message

Revision ID: 83ff37d65c62
Revises: 5b227271b081
Create Date: 2021-10-06 14:43:42.900782

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '83ff37d65c62'
down_revision = '5b227271b081'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('nombre_negocio', table_name='negocio')
    op.drop_index('nombre_negocio_2', table_name='negocio')
    op.drop_column('negocio', 'id_dueño_negocio')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('negocio', sa.Column('id_dueño_negocio', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.create_index('nombre_negocio_2', 'negocio', ['nombre_negocio'], unique=False)
    op.create_index('nombre_negocio', 'negocio', ['nombre_negocio'], unique=False)
    # ### end Alembic commands ###
