"""empty message

Revision ID: 845e615d2211
Revises: 77ca0479f9ab
Create Date: 2021-10-20 03:10:35.943057

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '845e615d2211'
down_revision = '77ca0479f9ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ventas_ibfk_2', 'ventas', type_='foreignkey')
    op.drop_column('ventas', 'detalleventa_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ventas', sa.Column('detalleventa_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('ventas_ibfk_2', 'ventas', 'detalledeventas', ['detalleventa_id'], ['id'])
    # ### end Alembic commands ###
