"""empty message

Revision ID: 8f6d051f1a89
Revises: 750f6584f33f
Create Date: 2021-10-06 14:12:50.849781

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8f6d051f1a89'
down_revision = '750f6584f33f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('producto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=True),
    sa.Column('codigo_barras', sa.String(length=120), nullable=True),
    sa.Column('id_categoria', sa.Integer(), nullable=True),
    sa.Column('precio_venta', sa.Float(precision=50), nullable=True),
    sa.Column('image', sa.String(length=50), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('fecha_ingreso', sa.String(length=50), nullable=False),
    sa.Column('proveedor', sa.String(length=50), nullable=False),
    sa.Column('costo_compra', sa.Float(precision=50), nullable=False),
    sa.Column('factura_proveedor', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_barras'),
    sa.UniqueConstraint('codigo_barras')
    )
    op.add_column('user', sa.Column('username', sa.String(length=120), nullable=False))
    op.add_column('user', sa.Column('name', sa.String(length=120), nullable=False))
    op.add_column('user', sa.Column('last_name', sa.String(length=120), nullable=False))
    op.add_column('user', sa.Column('role', sa.String(length=120), nullable=False))
    op.add_column('user', sa.Column('theme', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('font_preferene', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('negocio', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'user', ['negocio'])
    op.create_unique_constraint(None, 'user', ['username'])
    op.drop_column('user', 'is_active')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'negocio')
    op.drop_column('user', 'font_preferene')
    op.drop_column('user', 'theme')
    op.drop_column('user', 'role')
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'name')
    op.drop_column('user', 'username')
    op.drop_table('producto')
    # ### end Alembic commands ###
