"""empty message

Revision ID: b0166de0e13e
Revises: da1a9c85a43d
Create Date: 2021-10-07 14:40:43.486131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0166de0e13e'
down_revision = 'da1a9c85a43d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metodopago',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('num_pago', sa.String(length=120), nullable=True),
    sa.Column('nombre_metpag', sa.String(length=120), nullable=True),
    sa.Column('otros_datos', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('metodopago')
    # ### end Alembic commands ###
