"""empty message

Revision ID: c419e6ffbda4
Revises: d5fe060ba854
Create Date: 2021-10-06 14:28:40.408530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c419e6ffbda4'
down_revision = 'd5fe060ba854'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Negocio', sa.Column('nombre_negocio', sa.String(length=120), nullable=False))
    op.create_unique_constraint(None, 'Negocio', ['nombre_negocio'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Negocio', type_='unique')
    op.drop_column('Negocio', 'nombre_negocio')
    # ### end Alembic commands ###
