"""empty message

Revision ID: cd0f1832fb23
Revises: 907203a37266
Create Date: 2021-10-20 03:29:33.278299

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cd0f1832fb23'
down_revision = '907203a37266'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingresos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proveedor', sa.String(length=120), nullable=False),
    sa.Column('tipo_comprobante_ing', sa.String(length=120), nullable=False),
    sa.Column('numero_comprobante_ing', sa.String(length=120), nullable=False),
    sa.Column('fecha_ing', sa.String(length=50), nullable=False),
    sa.Column('impuesto_ing', sa.Float(), nullable=False),
    sa.Column('total_ing', sa.Float(), nullable=False),
    sa.Column('users_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['users_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('ingreso')
    op.add_column('detalleingreso', sa.Column('ingreso_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'detalleingreso', 'ingresos', ['ingreso_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'detalleingreso', type_='foreignkey')
    op.drop_column('detalleingreso', 'ingreso_id')
    op.create_table('ingreso',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('proveedor', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('tipo_comprobante_ing', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('numero_comprobante_ing', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('fecha_ing', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('impuesto_ing', mysql.FLOAT(), nullable=False),
    sa.Column('total_ing', mysql.FLOAT(), nullable=False),
    sa.Column('users_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['users_id'], ['usuarios.id'], name='ingreso_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('ingresos')
    # ### end Alembic commands ###
