"""empty message

Revision ID: d5fe060ba854
Revises: 8f6d051f1a89
Create Date: 2021-10-06 14:24:10.343614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5fe060ba854'
down_revision = '8f6d051f1a89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Negocio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_dueño_negocio', sa.Integer(), nullable=False),
    sa.Column('trabajadores', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id', 'id_dueño_negocio')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Negocio')
    # ### end Alembic commands ###
