"""empty message

Revision ID: da1a9c85a43d
Revises: 493b743b63ee
Create Date: 2021-10-07 06:48:58.896299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da1a9c85a43d'
down_revision = '493b743b63ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detalleingreso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_ingreso', sa.Integer(), nullable=False),
    sa.Column('id_articulo', sa.Integer(), nullable=False),
    sa.Column('cantidad_di', sa.Integer(), nullable=False),
    sa.Column('precio_di', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detalleingreso')
    # ### end Alembic commands ###
